<?php

/**
 * ProcessWire Table CSV Export Helper
 * by Adrian Jones
 *
 * Helper process module for generating CSV from a Table field
 *
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessTableCsvExport extends Process implements Module {

    /**
     * getModuleInfo is a module required by all modules to tell ProcessWire about them
     *
     * @return array
     *
     */
    public static function getModuleInfo() {
        return array(
            'title' => __('Process Table CSV Export'),
            'version' => 7,
            'summary' => __('Helper module for creating CSV to export'),
            'singular' => true,
            'autoload' => false,
            'requires' => 'TableCsvImportExport'
            );
    }

    /**
     * Name used for the page created in the admin
     *
     */
    const adminPageName = 'table-csv-export';



    /**
     * Initialize the module
     *
     */
    public function init() {
        parent::init();
    }

    /**
     * Executed when root url for module is accessed
     *
     */
    public function ___execute() {

        $p = wire('pages')->get((int) wire('input')->get->pid);
        $p->of(true); //needed to have dates etc formatted in the CSV
        $fieldName = wire('input')->get->fn;

        $csv = array();
        $i=0;
        foreach($p->$fieldName as $row){
            if($i==0 && wire('input')->get->nfr == 'checked'){
                foreach($row as $name => $value){
                    $csv[$i][] = $name;
                }
            }
            $i++;
            foreach($row as $name => $value){
                if($name!='id') $csv[$i][] = $value;
            }
        }

        header("Content-type: text/csv");
        header("Content-Disposition: attachment; filename=".$fieldName.".".wire('input')->get->ext);
        header("Pragma: no-cache");
        header("Expires: 0");

        $this->outputCSV($csv);
        exit;
    }


    public function outputCSV($data) {
        $output = fopen("php://output", "w");
        foreach ($data as $row) {
            fputcsv($output, $row, wire('input')->get->cs == "tab" ? chr(9) : wire('input')->get->cs, wire('input')->get->ce);
        }
        fclose($output);
    }


    /**
     * Install the module and create the page where it lives
     *
     */
    public function ___install() {

        $page = $this->getInstalledPage();
        $this->message("Installed to {$page->path}");

    }

    /**
     * Return the page that this Process is installed on
     *
     */
    protected function getInstalledPage() {

        $parent = $this->pages->get("name=page,parent=".$this->config->adminRootPageID);
        $page = $parent->child("name=" . self::adminPageName);

        if(!$page->id) {
            $page = new Page();
            $page->parent = $parent;
            $page->template = $this->templates->get('admin');
            $page->name = self::adminPageName;
            $page->title = "Table CSV Export";
            $page->process = $this;
            $page->status = Page::statusHidden;
            $page->sort = $parent->numChildren;
            $page->save();
        }

        return $page;
    }

    /**
     * Uninstall the module
     *
     */
    public function ___uninstall() {
        //$page = $this->getInstalledPage();
        $moduleID = $this->modules->getModuleID($this);
        $page = $this->pages->get("template=admin, process=$moduleID, name=" . self::adminPageName);
        if($page->id) {
            $this->message("Removed {$page->path}");
            $this->pages->delete($page);
        }
    }


}